### ISSUE TITLE
Some RSS feeds not being picked up, no feedback as to why (probably HTTPS)

### ISSUE THREAD

**Issue by spence91** [bearfrieze/litenin#13]
2 feeds, both RSS version 2.0, same structure, same order of elements.

One is recognised when it's added (http://xkcd.com/rss.xml) and items are added, one isn't (https://www.reddit.com/r/todayilearned/.rss) and no items are added. 

The only difference is that one is HTTPS - in fact every HTTPS feed doesn't work. It would be useful if the user was informed of this.

**Comment by spence91** [comment]
Apologies - that feed came through - just delayed.

**Comment by bearfrieze** [comment]
No worries. The feed fetching is currently not as fast or stable as I want it to be. I just monitored the server a few minutes ago, and there was a queue of 400 feeds that needed to be fetched. Thankfully the server seems to stay up at the moment instead of crashing.

Working on it, thanks for your feedback.
